<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<AssemblyName>SimpleTools</AssemblyName>
		<ApplicationIcon>app-icon.ico</ApplicationIcon>
		<RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
		<IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
		<SelfContained>true</SelfContained>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<ValidateExecutableReferencesMatchSelfContained>false</ValidateExecutableReferencesMatchSelfContained>
	</PropertyGroup>

	<ItemGroup>
		<Content Include="App-Icon.ico" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.1" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Resources\Resources.csproj" />
		<ProjectReference Include="..\ZeroMQBroker\ZeroMQBroker.csproj" />
		<ProjectReference Include="..\ZeroMQPublisher\ZeroMQPublisher.csproj" />
		<ProjectReference Include="..\ZeroMQSubscriber\ZeroMQSubscriber.csproj" />
	</ItemGroup>

</Project>
